framework:
    messenger:
        failure_transport: failed
        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0

            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0

            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    table_name: messenger_messages

        routing:
            '*': async_priority_low
