security:
    role_hierarchy:
        ROLE_USER:

    providers:
        user:
            id: User\Provider\UserProvider

    encoders:
        User\Entity\User:
            algorithm: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: /
            anonymous: lazy
            provider: user
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true
                httponly: true
                samesite: strict
                secure: true

            guard:
                authenticators:
                    - Security\Guard\LoginFormAuthenticator
            logout:
                path: security_logout
                target: page_index
