version: '3.7'
services:
    app:
        build: .
        container_name: app
        working_dir: /usr/src/app
        depends_on:
            - php
            - mysql
            - nginx
        networks:
            - webnet

    nginx:
        build: .docker/nginx
        container_name: nginx
        working_dir: /usr/src/app
        depends_on:
            - php
            - mysql
        networks:
            - webnet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role == manager]

    postgresql:
        build: .docker/postgresql
        container_name: postgresql
        working_dir: /usr/src/app
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - webnet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role == manager]

    php:
        build: .docker/php
        container_name: php
        working_dir: /usr/src/app
        depends_on:
            - mysql
        networks:
            - webnet
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

            placement:
                constraints: [node.role == manager]

networks:
    webnet: