services:
    cache.adapter.chained.app:
        class: Symfony\Component\Cache\Adapter\ChainAdapter
        public: false
        arguments:
            - ['@cache.redis']


framework:
    cache:
        default_redis_provider: '%env(REDIS_URL)%'
        app: cache.adapter.chained.app
        system: cache.adapter.redis
        pools:
            cache.apcu:
                adapter: cache.adapter.apcu
                default_lifetime: 86400

            cache.redis:
                adapter: cache.adapter.redis
                default_lifetime: 86400